version: '3'

services:

  npm: &npm
    image: mirotalksfu-npm:latest
    build:
        context: .
        dockerfile: Dockerfile
    container_name: mirotalksfu-npm
    volumes:
      - .:/src/
    command: -v
    entrypoint: ['npm']

  mirotalksfu:
    <<: *npm
    container_name: mirotalksfu
    hostname: mirotalksfu
    restart: unless-stopped
    ports:
        - '3010:3010/tcp'
        - '40000-40100:40000-40100/tcp'
        - '40000-40100:40000-40100/udp'
    command: start
