version: '3'

services:
    mirotalksfu:
        image: mirotalk/sfu:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mirotalksfu-npm
        volumes:
            - .:/src/
        command: -v
        entrypoint: ['npm']

    mirotalksfu:
        <<: *npm
        container_name: mirotalksfu
        hostname: mirotalksfu
        restart: unless-stopped
        volumes:
            - ./app/:/src/app/:ro
            - ./public/:/src/public/:ro
        ports:
            - '3010:3010/tcp'
            - '40000-40100:40000-40100/tcp'
            - '40000-40100:40000-40100/udp'
        command: start
